server:
  port: 8082

spring:     
    datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/avaliacao1_backend
    password: root
  jpa:
    hibernate:
      ddl-auto: update
 
mensagem: hello catalog