server:
  port: 8888

spring:
  application:
    name: config-server
  zipkin:
    base-url: http://zipkin-service:9411/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hakacarol/dh-especializacao-backend
          default-label: main
          search-paths:
            - 'cloud-config-avaliacao-2*'

#eureka:cd
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-service:8761/eureka/

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/