#spring:
#  application:
#    name: dh-account-service
#  cloud:
#    config:
##      uri: ${CONFIG_SERVER:http://localhost:8888}
#      import: optional:configserver:http://localhost:8888

spring:
  application:
    name: dh-account-service
  config:
    import: optional:configserver:http://localhost:8888
