#spring:
#  application:
#    name: dh-account-service
#  cloud:
#    config:
##      uri: ${CONFIG_SERVER:http://localhost:8888}
#      import: optional:configserver:http://localhost:8888
#server:
#  port: 8082
spring:
  application:
    name: dh-account-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dh-account-service